### ISSUE TITLE
Possible Data Issues

### ISSUE THREAD

**Issue by nathanhammond** [lshk-org/jyutping-table#4]
The following items in this list appear to have values that do not match their components. The source data from 10646hk.net JPTableFull.pdf *also* includes these values, but as a non-native speaker I am unable to ascertain their correctness.

```tsv
䇉	U+41C9	baak3 sing1
粌	U+7C8C	baak3 mai5
籿	U+7C7F	fan1 mai5
```

**Comment by nathanhammond** [comment]
Expanding on this, some of these may be bad handwriting that was propagated or [bad transcriptions](https://www.dampfkraft.com/ghost-characters.html).

It is easy to imagine how `竡	U+7AE1	baak3 sing1` and `䇉	U+41C9	baak3 sing1` could have been mistakenly read, written, transcribed, or entered. Looking at the characters in this multi-syllable set:

```tsv
籿	U+7C7F	fan1 mai5
粀	U+7C80	sap6 mai5
粁	U+7C81	cin1 mai5
粌	U+7C8C	baak3 mai5
粍	U+7C8D	hou4 mai5
粨	U+7CA8	baak3 mai5
糎	U+7CCE	lei4 mai5

䇆	U+41C6	sap6 sing1
䇉	U+41C9	baak3 sing1
竍	U+7ACD	sap6 sing1
竏	U+7ACF	cin1 sing1
竓	U+7AD3	hou4 sing1
竕	U+7AD5	fan1 sing1
竡	U+7AE1	baak3 sing1
竰	U+7AF0	lei4 sing1
𥪕	U+ED41	cin1 sing1

兙	U+5159	sap6 hak1
兛	U+515B	cin1 hak1
兝	U+515D	fan1 hak1
兞	U+515E	hou4 hak1
兡	U+5161	baak3 hak1
兣	U+5163	lei4 hak1

瓧	U+74E7	sap6 ngaa5
瓩	U+74E9	cin1 ngaa5
瓰	U+74F0	fan1 ngaa5
瓱	U+74F1	hou4 ngaa5
瓸	U+74F8	baak3 ngaa5
甅	U+7505	lei4 ngaa5
```

These are the odd ones that I feel like should get further scrutiny to identify their source:
```tsv
籿	U+7C7F	fan1 mai5
粌	U+7C8C	baak3 mai5
䇆	U+41C6	sap6 sing1
䇉	U+41C9	baak3 sing1
𥪕	U+ED41	cin1 sing1
```

**Comment by chaaklau** [comment]
```
籿	U+7C7F	fan1 mai5
粌	U+7C8C	baak3 mai5
䇆	U+41C6	sap6 sing1
䇉	U+41C9	baak3 sing1
𥪕	U+ED41	cin1 sing1
```
In fact I asked the exactly same question when I first worked on this list. These characters are quite counter-intuitive even to native users of 漢字.

The right components of these five characters come from 公寸、公引、公斗、公石、公秉 respectively. For instance 分米 (fan1 mai5, decimeter) is the "new standard for the unit 寸", and the 米 radical is used to indicate that it is a length measurement.

See this wikipedia page for more information: https://zh.wikipedia.org/wiki/計量用漢字

**Comment by nathanhammond** [comment]
Thank you for the additional information! I realized at some point that these looked like complete "sets," excepting those cases I set aside in my last comment (which I now have additional color for).

Now I'm off to *very* slowly read a Wikipedia page...

***

Aside: words.hk is absolutely invaluable. 我是中文大學雅禮中國語文研習所的學生。每天都會用words.hk。如果你們需要識做IT人，話畀我知！And yes, I'm aware that I've mixed formal and informal writing in that (and probably have grammar errors), but I'll get better, promise.
