### ISSUE TITLE
Omission: `訁`

### ISSUE THREAD

**Issue by nathanhammond** [lshk-org/jyutping-table#6]
I've created a script that [aims to reexport the same content](https://github.com/nathanhammond/parse-jyutping-table-full/blob/master/totsv.js) as this library to have independent implementations which can be used to check for consistency errors.

I've identified a single omission from this list that originates in the second table:
`訁 U+8A01 言字邊 jin4 zi6 bin1`

(Setting aside description vs. pronunciation questions from #3, this is omitted from the list when others like it appear.)

**Comment by chaaklau** [comment]
Added to list.tsv, closing.
